export const createM1SelectTypographyStyles = ({ isRtl = false } = {}) => ({
  container: (base) => ({
    ...base,
    fontFamily: "var(--app-font)",
    fontSize: "var(--font-body)",
    lineHeight: "var(--font-body-lh)",
    letterSpacing: 0,
    direction: isRtl ? "rtl" : "ltr",
  }),
  control: (base) => ({
    ...base,
    fontFamily: "var(--app-font)",
    fontSize: "var(--font-body)",
    lineHeight: "var(--font-body-lh)",
    letterSpacing: 0,
  }),
  input: (base) => ({ ...base, fontFamily: "var(--app-font)", fontSize: "var(--font-body)", lineHeight: "var(--font-body-lh)", color: "var(--text)" }),
  singleValue: (base) => ({ ...base, fontFamily: "var(--app-font)", fontSize: "var(--font-body)", lineHeight: "var(--font-body-lh)" }),
  placeholder: (base) => ({ ...base, fontFamily: "var(--app-font)", fontSize: "var(--font-body)", lineHeight: "var(--font-body-lh)" }),
  menuPortal: (base) => ({
    ...base,
    fontFamily: "var(--app-font)",
    fontSize: "var(--font-body)",
    lineHeight: "var(--font-body-lh)",
    letterSpacing: 0,
    direction: isRtl ? "rtl" : "ltr",
  }),
  menu: (base) => ({ ...base, fontFamily: "var(--app-font)", fontSize: "var(--font-body)", lineHeight: "var(--font-body-lh)", letterSpacing: 0 }),
  option: (base) => ({
    ...base,
    minHeight: "var(--control-height-md)",
    display: "flex",
    alignItems: "center",
    padding: "8px 12px",
    fontFamily: "var(--app-font)",
    fontSize: "var(--font-body)",
    fontWeight: 600,
    lineHeight: "var(--font-body-lh)",
    letterSpacing: 0,
    textAlign: isRtl ? "right" : "left",
  }),
  noOptionsMessage: (base) => ({ ...base, fontFamily: "var(--app-font)", fontSize: "var(--font-body)", lineHeight: "var(--font-body-lh)" }),
});
