FROM node:20-alpine AS builder
WORKDIR /app

ARG VITE_API_URL=
ARG VITE_ERP_HOST=erp.m1store-egy.com
ARG VITE_USE_SAME_ORIGIN_API=false

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_ERP_HOST=${VITE_ERP_HOST}
ENV VITE_USE_SAME_ORIGIN_API=${VITE_USE_SAME_ORIGIN_API}

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
