ALTER TABLE social_comment_automation_runs
  ADD COLUMN IF NOT EXISTS skipped_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS matched_config_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_post_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_platform_post_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_product_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS duplicate_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS config_found BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS config_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE social_comment_automation_run_audits
  ADD COLUMN IF NOT EXISTS skipped_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS matched_config_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_post_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_platform_post_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS resolved_product_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS duplicate_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS config_found BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS config_enabled BOOLEAN NOT NULL DEFAULT FALSE;
