import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("storefront category cards use full-bleed motion media", async () => {
  const source = await readFile(new URL("../src/storefront/Storefront.jsx", import.meta.url), "utf8");

  assert.match(source, /function HomeCategoryMotionMedia/);
  assert.match(source, /new IntersectionObserver/);
  assert.match(source, /muted[\s\S]*?loop[\s\S]*?playsInline/);
  assert.match(source, /min-h-\[390px\][\s\S]*?overflow-hidden/);
  assert.match(source, /HomeCategoryMotionMedia video=\{card\.video\} image=\{card\.image\}/);
  assert.doesNotMatch(source, /isRtl \? "فيديو" : "Video"/);
  assert.doesNotMatch(source, /isRtl \? "اكتشف القسم" : "Discover"/);
  assert.match(source, /h-full w-full object-cover transition/);
  assert.match(source, /match\?\.promo_video_url/);
  assert.match(source, /const MEN_CATEGORY_TRIAL_VIDEO_URL = "https:\/\/videos\.pexels\.com\/video-files\/33294342\/14180878_640_360_24fps\.mp4";/);
  assert.match(source, /id: "men"[\s\S]*?video: MEN_CATEGORY_TRIAL_VIDEO_URL/);
  assert.match(source, /id: "men"[\s\S]*?poster: "\/storefront\/category-posters\/men\.webp"/);
  assert.match(source, /const WOMEN_SLIPPERS_VIDEO_URL = "https:\/\/videos\.pexels\.com\/video-files\/6919220\/6919220-hd_720_1366_30fps\.mp4";/);
  assert.match(source, /const WOMEN_SLIPPERS_POSTER_URL = "https:\/\/images\.pexels\.com\/videos\/6919220\/pexels-photo-6919220\.jpeg\?auto=compress&cs=tinysrgb&w=480";/);
  assert.match(source, /id: "women-slippers"[\s\S]*?href: "\/products\?gender=women&type=slippers"/);
  assert.match(source, /id: "women-slippers"[\s\S]*?resolveProductTypeKey\(product\.product_type \|\| product\.productType\) === "slippers"/);
  assert.match(source, /id: "women-slippers"[\s\S]*?video: WOMEN_SLIPPERS_VIDEO_URL,[\s\S]*?poster: WOMEN_SLIPPERS_POSTER_URL,[\s\S]*?preferDefinitionVideo: true/);
  assert.match(source, /definition\.preferDefinitionVideo[\s\S]*?\? definition\.video/);
  assert.match(source, /const KIDS_CATEGORY_TRIAL_VIDEO_URL = "https:\/\/videos\.pexels\.com\/video-files\/8456205\/8456205-sd_640_360_25fps\.mp4";/);
  assert.match(source, /id: "kids"[\s\S]*?video: KIDS_CATEGORY_TRIAL_VIDEO_URL/);
  assert.match(source, /id: "kids"[\s\S]*?poster: "\/storefront\/category-posters\/kids\.webp"/);
  assert.match(source, /const SALE_CATEGORY_TRIAL_VIDEO_URL = "https:\/\/videos\.pexels\.com\/video-files\/5889624\/5889624-sd_426_240_25fps\.mp4";/);
  assert.match(source, /id: "offers"[\s\S]*?video: SALE_CATEGORY_TRIAL_VIDEO_URL,[\s\S]*?poster: "\/storefront\/category-posters\/sale\.webp",[\s\S]*?preferDefinitionVideo: true/);
  assert.match(source, /image: definition\.poster \|\| matchSlide\?\.image \|\| ""/);
  assert.match(source, /src=\{shouldLoadVideo \? video : undefined\}/);
  assert.match(source, /preload="none"/);
  assert.match(source, /rootMargin: "80px 0px"/);
  assert.match(source, /match\?\.media\?\.video_url \|\|[\s\S]*?definition\.video/);
  assert.match(source, /matchingProducts\.find\(\(product\) => homeProductWithImage\(product\)\)/);
  assert.match(source, /saleProducts\.find\(\(product\) => isAvailableProduct\(product\) && homeProductWithImage\(product\)\)/);
  assert.match(source, /if \(isOfferStory\(product\)\) return false/);
  assert.match(source, /const isExclusiveCategoryAudience/);
  assert.match(source, /audiences\.includes\("men"\) && audiences\.includes\("women"\)/);
  assert.match(source, /test: \(product\) => isExclusiveCategoryAudience\(product, "men"\)/);
  assert.match(source, /isExclusiveCategoryAudience\(product, "women"\) && resolveProductTypeKey/);
  assert.match(source, /uniqueProductsByIdentity\(\[\.\.\.womenCategoryProducts, \.\.\.homepageProductPool\]\)/);
  assert.match(source, /تسوّق الآن/);
});
