export const DEFAULT_THEME_ID = "light";
export const DEFAULT_ACCENT_ID = "default";
export const DEFAULT_DENSITY = "normal";

// M1 has one product accent. Keeping the accent API preserves backwards
// compatibility while preventing green/blue from becoming action colors.
export const ACCENTS = [
  { id: "default", name: "M1 Gold", primary: null, primarySoft: null },
  { id: "gold", name: "M1 Gold", primary: null, primarySoft: null },
];

const shared = {
  primary: "#a47a12",
  "primary-hover": "#8d670d",
  "primary-active": "#765608",
  "primary-contrast": "#1f1908",
  success: "#198754",
  warning: "#c47a08",
  danger: "#d14343",
  // Foreground for solid danger surfaces. Literals belong in the token layer;
  // primitives must never hardcode one.
  "danger-foreground": "#ffffff",
  // Neutral dialog scrim. Same in both themes; primitives must not inline it.
  "overlay-scrim": "rgba(0, 0, 0, 0.5)",
  info: "#4f6f8f",
  "radius-xs": "4px",
  "radius-sm": "7px",
  "radius-md": "10px",
  "radius-lg": "14px",
  "radius-xl": "18px",
  "control-height-sm": "32px",
  "control-height-md": "38px",
  "control-height-lg": "44px",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "20px",
  "space-6": "24px",
  "space-8": "32px",
  "font-ar": '"Cairo", "Tajawal", "Noto Sans Arabic", sans-serif',
  "font-en": '"Inter", "Segoe UI", sans-serif',
};

export const THEMES = [
  {
    id: "light",
    name: "M1 Light",
    description: "Calm, dense ERP surfaces with restrained M1 gold actions.",
    mode: "light",
    density: "normal",
    variables: {
      ...shared,
      bg: "#f3f3f1",
      surface: "#ffffff",
      card: "#ffffff",
      text: "#25231f",
      muted: "#716e67",
      border: "#dedbd3",
      "border-strong": "#c9c5bc",
      "primary-soft": "#fff7df",
      "success-soft": "#e9f7ef",
      "warning-soft": "#fff4df",
      "danger-soft": "#fceaea",
      "info-soft": "#edf3f8",
      "surface-soft": "#f7f7f5",
      "surface-raised": "#ffffff",
      "card-soft": "#f7f7f5",
      "sidebar": "#ececea",
      "topbar": "#1c1c1a",
      "topbar-text": "#f4f3ef",
      "text-secondary": "#5d5952",
      "text-tertiary": "#8b877f",
      "table-head": "#f7f7f5",
      "table-hover": "#faf9f6",
      // Row selection. The only table state without an existing token: head and
      // hover already lived here, selection was being improvised per page.
      "table-selected": "#fdf3da",
      "focus-ring": "rgba(164, 122, 18, 0.24)",
      shadow: "rgba(31, 29, 25, 0.08)",
      "shadow-card": "0 1px 2px rgba(31, 29, 25, 0.05)",
      "shadow-overlay": "0 16px 40px rgba(31, 29, 25, 0.16)",
    },
    preview: { sidebar: "#ececea", card: "#ffffff", button: "#a47a12", text: "#25231f", border: "#dedbd3" },
  },
  {
    id: "dark",
    name: "M1 Dark",
    description: "Neutral charcoal ERP surfaces with readable dense data.",
    mode: "dark",
    density: "normal",
    variables: {
      ...shared,
      primary: "#d0a632",
      "primary-hover": "#dfb842",
      "primary-active": "#b78d22",
      bg: "#171715",
      surface: "#232321",
      card: "#232321",
      text: "#efeee9",
      muted: "#a19e96",
      border: "#393936",
      "border-strong": "#4b4a46",
      "primary-soft": "#352d18",
      success: "#42b883",
      "success-soft": "#183529",
      warning: "#e0a23a",
      "warning-soft": "#3a2d17",
      danger: "#ef6b6b",
      "danger-soft": "#3b2020",
      info: "#82a4c2",
      "info-soft": "#1f2d38",
      "surface-soft": "#2a2a27",
      "surface-raised": "#292926",
      "card-soft": "#2a2a27",
      sidebar: "#1d1d1b",
      topbar: "#10100f",
      "topbar-text": "#f4f3ef",
      "text-secondary": "#c5c2ba",
      "text-tertiary": "#918e87",
      "table-head": "#2c2c29",
      "table-hover": "#282825",
      "table-selected": "#3a3119",
      "focus-ring": "rgba(208, 166, 50, 0.28)",
      shadow: "rgba(0, 0, 0, 0.32)",
      "shadow-card": "0 1px 2px rgba(0, 0, 0, 0.24)",
      "shadow-overlay": "0 18px 48px rgba(0, 0, 0, 0.42)",
    },
    preview: { sidebar: "#1d1d1b", card: "#232321", button: "#d0a632", text: "#efeee9", border: "#393936" },
  },
];

export const THEME_MAP = Object.fromEntries(THEMES.map((theme) => [theme.id, theme]));
