import { api } from "../../../shared/api/api";

const tokenPath = (token) => `/manager-portal/${encodeURIComponent(token)}`;

export const managerPortalApi = {
  me: (token, options = {}) => api.get(`${tokenPath(token)}/me`, options),
  dashboard: (token, params = {}, options = {}) => api.get(`${tokenPath(token)}/dashboard`, { ...options, params }),
  invoice: (token, invoiceId) => api.get(`${tokenPath(token)}/invoices/${encodeURIComponent(invoiceId)}`),
  staff: (token, options = {}) => api.get(`${tokenPath(token)}/staff`, options),
  employeeDetails: (token, employeeId, params = {}, options = {}) => api.get(`${tokenPath(token)}/staff/${encodeURIComponent(employeeId)}/details`, { ...options, params }),
  createEmployeeAdjustment: (token, employeeId, payload) => api.post(`${tokenPath(token)}/staff/${encodeURIComponent(employeeId)}/adjustments`, payload),
  deleteEmployeeAdjustment: (token, employeeId, kind, adjustmentId) => api.delete(`${tokenPath(token)}/staff/${encodeURIComponent(employeeId)}/adjustments/${encodeURIComponent(kind)}/${encodeURIComponent(adjustmentId)}`),
  correctEmployeeAttendance: (token, employeeId, payload) => api.post(`${tokenPath(token)}/staff/${encodeURIComponent(employeeId)}/attendance`, payload),
  reviewAdvanceRequest: (token, requestId, payload) => api.patch(`${tokenPath(token)}/advance-requests/${encodeURIComponent(requestId)}`, payload),
  tasks: (token, options = {}) => api.get(`${tokenPath(token)}/tasks`, options),
  sales: (token, options = {}) => api.get(`${tokenPath(token)}/sales`, options),
  operations: (token, params = {}, options = {}) => api.get(`${tokenPath(token)}/operations`, { ...options, params }),
  stockAlerts: (token, options = {}) => api.get(`${tokenPath(token)}/stock-alerts`, options),
  inventoryApprovals: (token, params = {}, options = {}) => api.get(`${tokenPath(token)}/inventory-approvals`, { ...options, params }),
  inventoryApproval: (token, sessionId) => api.get(`${tokenPath(token)}/inventory-approvals/${encodeURIComponent(sessionId)}`),
  approveInventoryApproval: (token, sessionId) => api.post(`${tokenPath(token)}/inventory-approvals/${encodeURIComponent(sessionId)}/approve`),
  rejectInventoryApproval: (token, sessionId, payload = {}) => api.post(`${tokenPath(token)}/inventory-approvals/${encodeURIComponent(sessionId)}/reject`, payload),
  pushPublicKey: (token, options = {}) => api.get(`${tokenPath(token)}/push/public-key`, options),
  subscribePush: (token, payload) => api.post(`${tokenPath(token)}/push/subscribe`, payload),
  testPush: (token, payload = {}) => api.post(`${tokenPath(token)}/push/test`, payload),
  unsubscribePush: (token, payload = {}) => api.post(`${tokenPath(token)}/push/unsubscribe`, payload),
  notifications: (token, params = {}, options = {}) => api.get(`${tokenPath(token)}/notifications`, { ...options, params }),
  markNotificationRead: (token, id) => api.post(`${tokenPath(token)}/notifications/${encodeURIComponent(id)}/read`),
  markAllNotificationsRead: (token) => api.post(`${tokenPath(token)}/notifications/read-all`),
  chat: (token, threadId = null, options = {}) => api.get(`${tokenPath(token)}/chat`, { ...options, params: threadId ? { thread_id: threadId } : {} }),
  chatThread: (token, threadId, options = {}) => api.get(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}`, options),
  markChatDelivered: (token, threadId, upToMessageId = null) => api.post(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}/delivered`, { up_to_message_id: upToMessageId }),
  sendChatMessage: (token, threadId, formData) => api.post(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}/messages`, formData),
  markChatRead: (token, threadId) => api.post(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}/read`),
  ringChat: (token, threadId) => api.post(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}/ring`, {}),
  answerChatRing: (token, threadId, messageId) => api.post(`${tokenPath(token)}/chat/${encodeURIComponent(threadId)}/ring/${encodeURIComponent(messageId)}/answer`, {}),
  createTask: (token, payload) => api.post(`${tokenPath(token)}/tasks`, payload),
  updateTask: (token, id, payload = {}) => api.patch(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}`, payload),
  deleteTask: (token, id) => api.delete(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}`),
  approveTask: (token, id, payload = {}) => api.patch(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}/approve`, payload),
  rejectTask: (token, id, payload = {}) => api.patch(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}/reject`, payload),
  reopenTask: (token, id, payload = {}) => api.patch(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}/reopen`, payload),
  noteTask: (token, id, payload = {}) => api.post(`${tokenPath(token)}/tasks/${encodeURIComponent(id)}/notes`, payload),
  updateSettings: (token, payload) => api.patch(`${tokenPath(token)}/settings`, payload),
  unlockProfit: (token, password) => api.post(`${tokenPath(token)}/profit/unlock`, { password }),
  lockProfit: (token, profitToken) => api.post(`${tokenPath(token)}/profit/lock`, { profit_token: profitToken }),
  salesWithProfit: (token, profitToken, options = {}) => api.get(`${tokenPath(token)}/sales`, { ...options, headers: { ...(options.headers || {}), "X-Profit-Authorization": `Bearer ${profitToken}` } }),
};

export default managerPortalApi;
