import { ORDER_LIFECYCLE_STATUSES, ORDER_STATUS_LABELS } from "./orderStatus.js";
import { defaultEgyptShippingLocations } from "./egyptShippingLocations.js";
import { BARCODE_PRINT_DEFAULTS, DISPLAY_REFILL_BARCODE_DEFAULTS } from "./barcodePrintSettings.js";
import { SHIPMENT_NOTIFICATION_DEFAULTS } from "./shipmentNotificationTemplates.js";
import { ABANDONED_CART_DEFAULTS } from "./abandonedCartDefaults.js";
import {
  WHATSAPP_AUTOMATION_EXPIRY_DEFAULTS,
  WHATSAPP_MESSAGE_VARIANT_DEFAULTS,
  WHATSAPP_QUEUE_CATEGORY_DEFAULTS,
  WHATSAPP_QUEUE_DEFAULTS,
} from "./whatsappQueueDefaults.js";

const label = (en, ar) => ({ en, ar });

export const settingsCategories = [
  { key: "general", label: label("General", "عام"), description: label("Company identity, branding, currency, language, formats, and preferences.", "هوية الشركة والعلامة التجارية والعملة واللغة والتنسيقات والتفضيلات.") },
  { key: "storefront", label: label("Storefront", "المتجر"), description: label("Store identity, homepage, catalog, search, product cards, SEO, and notifications.", "هوية المتجر والرئيسية والكتالوج والبحث وبطاقات المنتجات والسيو والإشعارات.") },
  { key: "shipping", label: label("Shipping", "الشحن"), description: label("Shipping zones, governorates, free shipping, COD rules, proof rules, and providers.", "مناطق الشحن والمحافظات والشحن المجاني وقواعد الدفع عند الاستلام وإثبات الدفع وشركات الشحن.") },
  { key: "payments", label: label("Payments", "المدفوعات"), description: label("Cash on delivery, wallets, gateways, and payment instructions.", "الدفع عند الاستلام والمحافظ وبوابات الدفع وتعليمات الدفع.") },
  { key: "ai_channels", label: label("AI & Marketing", "الذكاء والتسويق"), description: label("AI assistant, AI inbox, marketing automation, and Meta integrations.", "مساعد الذكاء وصندوق الوارد والأتمتة التسويقية وتكاملات Meta.") },
  { key: "orders", label: label("Orders", "الطلبات"), description: label("Order lifecycle, invoices, fulfillment, stock reservation, and customer messages.", "دورة الطلبات والفواتير والتجهيز وحجز المخزون ورسائل العملاء.") },
  { key: "pos", label: label("POS", "نقطة البيع"), description: label("Cashier defaults, discounts, receipt, and cart behavior.", "إعدادات الكاشير والخصومات والإيصال وسلة البيع.") },
  { key: "inventory", label: label("Inventory", "المخزون"), description: label("Warehouse defaults, SKU rules, stock reservations, and variants.", "إعدادات المخازن والأكواد وحجز المخزون والمنتجات المتغيرة.") },
  { key: "accounting", label: label("Accounting", "الحسابات"), description: label("Posting defaults, ledger accounts, tax, and VAT behavior.", "إعدادات القيود والحسابات والضرائب والقيمة المضافة.") },
  { key: "employees", label: label("Employees", "الموظفون"), description: label("Attendance, payroll, commissions, and employee wallet settings.", "إعدادات الحضور والمرتبات والعمولات ومحفظة الموظف.") },
  { key: "notifications", label: label("Notifications", "الإشعارات"), description: label("Alert types and delivery channels.", "أنواع التنبيهات وقنوات الإرسال.") },
  { key: "security", label: label("Security & Users", "الأمان والمستخدمون"), description: label("Session, password, audit, permissions shortcuts, and future API tokens.", "الجلسات وكلمات المرور والتدقيق واختصارات الصلاحيات ومفاتيح API القادمة.") },
  { key: "barcode_printing", label: label("Barcode Printing", "إعدادات طباعة الباركود"), description: label("Paper presets, label layout, barcode sizing, and print label visibility.", "إعدادات الورق وتخطيط الملصقات وحجم الباركود والعناصر الظاهرة أثناء الطباعة.") },
];

const option = (value, en, ar) => ({ value, label: label(en, ar) });

// Offered as a list rather than free text: a typo here would silently move the
// attendance business day, and the shop only ever operates in one of these.
const attendanceTimeZoneOptions = [
  option("Africa/Cairo", "Cairo (Egypt)", "القاهرة (مصر)"),
  option("Asia/Riyadh", "Riyadh (Saudi Arabia)", "الرياض (السعودية)"),
  option("Asia/Dubai", "Dubai (UAE)", "دبي (الإمارات)"),
  option("Asia/Kuwait", "Kuwait", "الكويت"),
  option("Asia/Amman", "Amman (Jordan)", "عمّان (الأردن)"),
  option("Asia/Baghdad", "Baghdad (Iraq)", "بغداد (العراق)"),
  option("Africa/Khartoum", "Khartoum (Sudan)", "الخرطوم (السودان)"),
  option("Africa/Casablanca", "Casablanca (Morocco)", "الدار البيضاء (المغرب)"),
  option("Europe/Istanbul", "Istanbul (Türkiye)", "إسطنبول (تركيا)"),
  option("UTC", "UTC", "التوقيت العالمي UTC"),
];

const defaultStorefrontShippingZones = [
  { id: "cairo", governorate: "Cairo", city: "", area: "", price: 70, requires_shipping_proof: true, estimated_delivery_text: "2-4 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "giza", governorate: "Giza", city: "", area: "", price: 70, requires_shipping_proof: true, estimated_delivery_text: "2-4 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "alexandria", governorate: "Alexandria", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "dakahlia", governorate: "Dakahlia", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "red-sea", governorate: "Red Sea", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "beheira", governorate: "Beheira", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "fayoum", governorate: "Fayoum", city: "", area: "", price: 80, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "gharbia", governorate: "Gharbia", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "ismailia", governorate: "Ismailia", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "menofia", governorate: "Menofia", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "minya", governorate: "Minya", city: "", area: "", price: 85, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "qalyubia", governorate: "Qalyubia", city: "", area: "", price: 70, requires_shipping_proof: true, estimated_delivery_text: "2-4 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "new-valley", governorate: "New Valley", city: "", area: "", price: 95, requires_shipping_proof: true, estimated_delivery_text: "4-7 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "suez", governorate: "Suez", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "aswan", governorate: "Aswan", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "assiut", governorate: "Assiut", city: "", area: "", price: 85, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "beni-suef", governorate: "Beni Suef", city: "", area: "", price: 80, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "port-said", governorate: "Port Said", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "damietta", governorate: "Damietta", city: "", area: "", price: 45, requires_shipping_proof: false, estimated_delivery_text: "1-2 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "new-damietta", governorate: "Damietta", city: "New Damietta", area: "", price: 40, requires_shipping_proof: false, estimated_delivery_text: "1-2 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "sharqia", governorate: "Sharqia", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "south-sinai", governorate: "South Sinai", city: "", area: "", price: 95, requires_shipping_proof: true, estimated_delivery_text: "4-7 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "kafr-el-sheikh", governorate: "Kafr El Sheikh", city: "", area: "", price: 75, requires_shipping_proof: true, estimated_delivery_text: "2-5 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "matrouh", governorate: "Matrouh", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "luxor", governorate: "Luxor", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "qena", governorate: "Qena", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "north-sinai", governorate: "North Sinai", city: "", area: "", price: 95, requires_shipping_proof: true, estimated_delivery_text: "4-7 business days", provider: "manual", free_shipping_threshold: 0, active: true },
  { id: "sohag", governorate: "Sohag", city: "", area: "", price: 90, requires_shipping_proof: true, estimated_delivery_text: "3-6 business days", provider: "manual", free_shipping_threshold: 0, active: true },
];

const definitions = [
  ["general.company_name", "general", "text", "", "Company name", "اسم الشركة", "Shown on invoices, storefront, and receipts.", "يظهر في الفواتير والمتجر والإيصالات.", { isPublic: true, usedBy: ["Invoices", "POS", "Storefront"] }],
  ["general.company_logo_url", "general", "url", "", "Company logo", "شعار الشركة", "Public logo URL used by customer-facing views.", "رابط الشعار المستخدم في الواجهات العامة.", { isPublic: true, usedBy: ["Invoices", "Storefront"] }],
  ["general.favicon_url", "general", "url", "", "Favicon", "أيقونة الموقع", "Public favicon URL used by browser tabs.", "رابط الأيقونة الظاهرة في المتصفح.", { isPublic: true, usedBy: ["Storefront", "ERP"] }],
  ["general.default_language", "general", "select", "ar", "Default language", "اللغة الافتراضية", "Default ERP language for new sessions.", "لغة النظام الافتراضية للجلسات الجديدة.", { options: [option("ar", "Arabic", "العربية"), option("en", "English", "الإنجليزية")], isPublic: true, usedBy: ["ERP", "Storefront"] }],
  // Store-wide appearance default (fonts + shape + control size). Edited only
  // from /settings/appearance — the Settings Center hides it from the General
  // form. Public so every client can apply it before login.
  ["general.appearance_profile", "general", "json", null, "Appearance profile", "ملف المظهر", "Default fonts, corner radius, and control size for every ERP user who has not chosen their own.", "الخطوط والزوايا وحجم العناصر الافتراضية لكل مستخدم لم يختر مظهره الخاص.", { isPublic: true, usedBy: ["ERP"] }],
  ["general.default_direction", "general", "select", "auto", "Default direction", "اتجاه العرض", "Controls RTL/LTR behavior when language is not explicit.", "يتحكم في RTL/LTR عند عدم تحديد اللغة.", { options: [option("auto", "Auto", "تلقائي"), option("rtl", "RTL", "يمين لليسار"), option("ltr", "LTR", "يسار لليمين")], isPublic: true, usedBy: ["ERP", "Storefront"] }],
  ["general.default_currency", "general", "text", "EGP", "Default currency", "العملة الافتراضية", "Primary currency code.", "كود العملة الأساسي.", { validation: { maxLength: 8 }, isPublic: true, usedBy: ["POS", "Orders", "Accounting"] }],
  ["general.currency_symbol", "general", "text", "ج.م", "Currency symbol", "رمز العملة", "Displayed beside money amounts.", "يعرض بجانب المبالغ.", { validation: { maxLength: 8 }, isPublic: true, usedBy: ["POS", "Payroll", "Storefront"] }],
  ["general.number_format", "general", "select", "en-US", "Number format", "تنسيق الأرقام", "Locale used for numbers.", "اللغة المستخدمة لتنسيق الأرقام.", { options: [option("en-US", "English", "إنجليزي"), option("ar-EG", "Arabic Egypt", "عربي مصر")] }],
  ["general.date_format", "general", "select", "yyyy-MM-dd", "Date format", "تنسيق التاريخ", "Preferred date format.", "تنسيق التاريخ المفضل.", { options: [option("yyyy-MM-dd", "2026-05-29", "2026-05-29"), option("dd/MM/yyyy", "29/05/2026", "29/05/2026")] }],
  ["general.time_format", "general", "select", "24h", "Time format", "تنسيق الوقت", "Preferred time display.", "طريقة عرض الوقت.", { options: [option("24h", "24 hour", "24 ساعة"), option("12h", "12 hour", "12 ساعة")] }],
  ["general.timezone", "general", "text", "Africa/Cairo", "Timezone", "المنطقة الزمنية", "Default business timezone.", "المنطقة الزمنية الافتراضية.", { isPublic: true, usedBy: ["Attendance", "Payroll", "Orders"] }],
  ["general.default_country", "general", "text", "Egypt", "Default country", "الدولة الافتراضية", "Default customer and branch country.", "الدولة الافتراضية للعملاء والفروع."],
  ["general.default_city", "general", "text", "Cairo", "Default city/governorate", "المدينة/المحافظة", "Default city for addresses.", "المدينة الافتراضية للعناوين."],
  ["general.business_working_days", "general", "multiselect", ["sat", "sun", "mon", "tue", "wed", "thu"], "Business working days", "أيام العمل", "Used by attendance and fulfillment planning.", "تستخدم في الحضور وتجهيز الطلبات.", { options: [option("sat", "Saturday", "السبت"), option("sun", "Sunday", "الأحد"), option("mon", "Monday", "الإثنين"), option("tue", "Tuesday", "الثلاثاء"), option("wed", "Wednesday", "الأربعاء"), option("thu", "Thursday", "الخميس"), option("fri", "Friday", "الجمعة")] }],
  ["general.business_hours", "general", "json", { start: "10:00", end: "22:00" }, "Business hours", "ساعات العمل", "JSON object with start and end times.", "كائن JSON يحتوي بداية ونهاية العمل."],
  ["general.default_branch_id", "general", "text", "", "Default branch", "الفرع الافتراضي", "Default branch for operations without explicit branch.", "الفرع الافتراضي للعمليات بدون فرع محدد.", { usedBy: ["POS", "Orders", "Inventory"] }],
  ["general.default_warehouse_id", "general", "text", "", "Default warehouse", "المخزن الافتراضي", "Default warehouse for stock operations.", "المخزن الافتراضي لحركات المخزون.", { usedBy: ["POS", "Orders", "Inventory"] }],
  ["general.default_pos_treasury_account_id", "general", "text", "", "Default POS treasury account", "خزينة الكاشير الافتراضية", "Cash account used by POS when not overridden.", "حساب النقدية المستخدم في نقطة البيع عند عدم التحديد."],
  ["general.barcode_print_paper_size", "general", "select", BARCODE_PRINT_DEFAULTS.paperSize, "Barcode paper size", "مقاس ورق الباركود", "Select the paper preset used by barcode printing.", "اختر مقاس الورق المستخدم في طباعة الباركود.", { options: [option("a4", "A4", "A4"), option("a5", "A5", "A5"), option("thermal", "Thermal Label", "ملصق حراري"), option("custom", "Custom", "مخصص")], usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_custom_paper_width_mm", "general", "number", BARCODE_PRINT_DEFAULTS.customPaperWidthMm, "Custom paper width (mm)", "عرض الورق المخصص (مم)", "Custom sheet width in millimeters.", "عرض الورق المخصص بالمليمتر.", { validation: { min: 20, max: 500 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_custom_paper_height_mm", "general", "number", BARCODE_PRINT_DEFAULTS.customPaperHeightMm, "Custom paper height (mm)", "ارتفاع الورق المخصص (مم)", "Custom sheet height in millimeters.", "ارتفاع الورق المخصص بالمليمتر.", { validation: { min: 20, max: 500 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_label_width_mm", "general", "number", BARCODE_PRINT_DEFAULTS.labelWidthMm, "Label width (mm)", "عرض الملصق (مم)", "Single barcode label width.", "عرض ملصق الباركود الواحد.", { validation: { min: 15, max: 200 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_label_height_mm", "general", "number", BARCODE_PRINT_DEFAULTS.labelHeightMm, "Label height (mm)", "ارتفاع الملصق (مم)", "Single barcode label height.", "ارتفاع ملصق الباركود الواحد.", { validation: { min: 15, max: 200 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_labels_per_row", "general", "number", BARCODE_PRINT_DEFAULTS.labelsPerRow, "Labels per row", "عدد الملصقات في الصف", "How many labels appear in each print row.", "عدد الملصقات التي تظهر في كل صف.", { validation: { min: 1, max: 12 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_labels_per_page", "general", "number", BARCODE_PRINT_DEFAULTS.labelsPerPage, "Labels per page", "عدد الملصقات في الصفحة", "Maximum labels rendered on a page. Use 0 for automatic flow.", "أقصى عدد ملصقات في الصفحة. استخدم 0 للتدفق التلقائي.", { validation: { min: 0, max: 999 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_gap_mm", "general", "number", BARCODE_PRINT_DEFAULTS.gapMm, "Gap between labels (mm)", "المسافة بين الملصقات (مم)", "Spacing between labels.", "المسافة بين الملصقات.", { validation: { min: 0, max: 40 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_margin_top_mm", "general", "number", BARCODE_PRINT_DEFAULTS.marginTopMm, "Page margin top (mm)", "هامش أعلى الصفحة (مم)", "Top page margin.", "الهامش العلوي للصفحة.", { validation: { min: 0, max: 40 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_margin_right_mm", "general", "number", BARCODE_PRINT_DEFAULTS.marginRightMm, "Page margin right (mm)", "هامش يمين الصفحة (مم)", "Right page margin.", "الهامش الأيمن للصفحة.", { validation: { min: 0, max: 40 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_margin_bottom_mm", "general", "number", BARCODE_PRINT_DEFAULTS.marginBottomMm, "Page margin bottom (mm)", "هامش أسفل الصفحة (مم)", "Bottom page margin.", "الهامش السفلي للصفحة.", { validation: { min: 0, max: 40 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_margin_left_mm", "general", "number", BARCODE_PRINT_DEFAULTS.marginLeftMm, "Page margin left (mm)", "هامش يسار الصفحة (مم)", "Left page margin.", "الهامش الأيسر للصفحة.", { validation: { min: 0, max: 40 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_barcode_width_scale", "general", "number", BARCODE_PRINT_DEFAULTS.barcodeWidthScale, "Barcode width scale (%)", "مقياس عرض الباركود (%)", "Scale the barcode width relative to the base layout.", "تكبير أو تصغير عرض الباركود نسبةً إلى التخطيط الأساسي.", { validation: { min: 40, max: 200 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_barcode_height", "general", "number", BARCODE_PRINT_DEFAULTS.barcodeHeight, "Barcode height", "ارتفاع الباركود", "Barcode SVG height used in preview and print.", "ارتفاع الباركود المستخدم في المعاينة والطباعة.", { validation: { min: 36, max: 160 }, usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_show_product_image", "general", "boolean", BARCODE_PRINT_DEFAULTS.showProductImage, "Show product image", "إظهار صورة المنتج", "Display the product image on the barcode label.", "إظهار صورة المنتج داخل ملصق الباركود.", { usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_show_product_name", "general", "boolean", BARCODE_PRINT_DEFAULTS.showProductName, "Show product name", "إظهار اسم المنتج", "Display the product name on the barcode label.", "إظهار اسم المنتج داخل ملصق الباركود.", { usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_show_price", "general", "boolean", BARCODE_PRINT_DEFAULTS.showPrice, "Show price", "إظهار السعر", "Display the sale price on the barcode label.", "إظهار السعر داخل ملصق الباركود.", { usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_show_sku_article", "general", "boolean", BARCODE_PRINT_DEFAULTS.showSkuArticle, "Show SKU / article", "إظهار SKU / الكود", "Display the SKU or article code on the barcode label.", "إظهار SKU أو كود الصنف داخل الملصق.", { usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_show_size_color", "general", "boolean", BARCODE_PRINT_DEFAULTS.showSizeColor, "Show size / color", "إظهار المقاس / اللون", "Display size and color on the barcode label.", "إظهار المقاس واللون داخل الملصق.", { usedBy: ["Barcode Labels"] }],
  ["general.barcode_print_default_printer", "general", "text", DISPLAY_REFILL_BARCODE_DEFAULTS.defaultPrinter, "Default barcode printer", "الطابعة الافتراضية للباركود", "Preferred printer name for barcode labels. Browser print still controls the final printer selection.", "اسم الطابعة المفضل لملصقات الباركود. يظل اختيار الطابعة النهائي من خلال نافذة الطباعة في المتصفح.", { validation: { maxLength: 160 }, usedBy: ["Display Shortages", "Barcode Labels"] }],
  ["general.barcode_print_display_label_size", "general", "select", DISPLAY_REFILL_BARCODE_DEFAULTS.labelSize, "Label size", "مقاس الملصق", "Default label size used when printing from display shortages.", "مقاس الملصق الافتراضي المستخدم عند الطباعة من نواقص العرض.", { options: [option("40x30", "40×30 mm", "40×30 مم"), option("50x30", "50×30 mm", "50×30 مم"), option("50x100", "50×100 mm", "50×100 مم")], usedBy: ["Display Shortages"] }],
  ["general.barcode_print_display_copies", "general", "number", DISPLAY_REFILL_BARCODE_DEFAULTS.copies, "Number of copies", "عدد النسخ", "How many barcode labels to print for each display shortage item.", "عدد ملصقات الباركود التي تتم طباعتها لكل عنصر من نواقص العرض.", { validation: { min: 1, max: 999 }, usedBy: ["Display Shortages"] }],
  ["general.barcode_print_auto_print_on_displayed", "general", "boolean", DISPLAY_REFILL_BARCODE_DEFAULTS.autoPrintWhenDisplayed, "Auto print when marking as displayed", "الطباعة التلقائية عند تعليم العنصر كمعروض", "Automatically print barcode labels after the Displayed action succeeds.", "طباعة ملصقات الباركود تلقائيًا بعد نجاح إجراء تم العرض.", { usedBy: ["Display Shortages"] }],

  ["orders.order_number_prefix", "orders", "text", "ORD", "Order number prefix", "بادئة رقم الطلب", "Prefix for generated order numbers.", "بادئة أرقام الطلبات."],
  ["orders.invoice_number_prefix", "orders", "text", "INV", "Invoice number prefix", "بادئة رقم الفاتورة", "Prefix for invoice numbers.", "بادئة أرقام الفواتير."],
  ["orders.auto_confirm_website_orders", "orders", "boolean", false, "Auto-confirm website orders", "تأكيد طلبات الموقع تلقائيا", "Move new website orders directly to confirmed.", "نقل طلبات الموقع الجديدة إلى مؤكد تلقائيا."],
  ["orders.require_admin_approval_before_fulfillment", "orders", "boolean", true, "Require approval before fulfillment", "موافقة قبل التجهيز", "Prevents fulfillment before admin approval.", "يمنع التجهيز قبل موافقة الإدارة."],
  ["orders.allow_cod", "payments", "boolean", true, "Allow COD", "السماح بالدفع عند الاستلام", "Enable cash on delivery for website orders.", "تفعيل الدفع عند الاستلام لطلبات الموقع.", { isPublic: true }],
  ["payments.instapay_enabled", "payments", "boolean", true, "Instapay enabled", "تفعيل إنستاباي", "Allow customers to pay shipping or order deposits through Instapay.", "السماح للعملاء بدفع الشحن أو مقدم الطلب عبر إنستاباي.", { isPublic: true, placeholder: true }],
  ["payments.instapay_handle", "payments", "text", "", "Instapay handle", "حساب إنستاباي", "Customer-facing Instapay handle.", "حساب إنستاباي الظاهر للعملاء.", { isPublic: true }],
  ["payments.vodafone_cash_enabled", "payments", "boolean", true, "Vodafone Cash enabled", "تفعيل فودافون كاش", "Allow Vodafone Cash transfers.", "السماح بتحويلات فودافون كاش.", { isPublic: true, placeholder: true }],
  ["payments.vodafone_cash_number", "payments", "text", "", "Vodafone Cash number", "رقم فودافون كاش", "Customer-facing wallet number.", "رقم المحفظة الظاهر للعملاء.", { isPublic: true }],
  ["payments.paymob_enabled", "payments", "boolean", false, "Paymob enabled", "تفعيل Paymob", "Enable Paymob online payments when credentials are configured.", "تفعيل Paymob عند ضبط بيانات التكامل.", { placeholder: true }],
  ["payments.stripe_enabled", "payments", "boolean", false, "Stripe enabled", "تفعيل Stripe", "Placeholder for Stripe online payments.", "عنصر جاهز لمدفوعات Stripe.", { placeholder: true }],
  ["payments.instructions", "payments", "textarea", "", "Payment instructions", "تعليمات الدفع", "Instructions shown to customers during checkout.", "تعليمات تظهر للعملاء أثناء الدفع.", { isPublic: true }],
  ["orders.allow_store_pickup", "orders", "boolean", true, "Allow store pickup", "السماح بالاستلام من الفرع", "Enable pickup option on checkout.", "تفعيل خيار الاستلام من الفرع.", { isPublic: true }],
  ["orders.default_website_order_status", "orders", "select", "pending", "Default website order status", "حالة طلب الموقع الافتراضية", "Initial status for website orders.", "الحالة الأولية لطلبات الموقع.", { options: ORDER_LIFECYCLE_STATUSES.map((status) => option(status, ORDER_STATUS_LABELS[status] || status, ORDER_STATUS_LABELS[status] || status)) }],
  ["orders.default_pos_order_status", "orders", "select", "delivered", "Default POS order status", "حالة طلب الكاشير", "Status used after POS checkout.", "الحالة المستخدمة بعد البيع من الكاشير.", { options: ORDER_LIFECYCLE_STATUSES.map((status) => option(status, ORDER_STATUS_LABELS[status] || status, ORDER_STATUS_LABELS[status] || status)) }],
  ["orders.reserve_stock_on_website_order", "orders", "boolean", true, "Reserve stock on website order", "حجز المخزون لطلبات الموقع", "Reserve stock as soon as a website order is created.", "حجز المخزون عند إنشاء طلب من الموقع."],
  ["orders.reserve_stock_expiry_minutes", "orders", "number", 60, "Reserve stock expiry minutes", "مدة حجز المخزون بالدقائق", "Release reserved stock after this period.", "فك حجز المخزون بعد هذه المدة.", { validation: { min: 0 } }],
  ["orders.cancel_unpaid_after_minutes", "orders", "number", 1440, "Cancel unpaid orders after minutes", "إلغاء غير المدفوع بعد دقائق", "Automatically cancel unpaid orders after this duration.", "إلغاء الطلبات غير المدفوعة بعد هذه المدة.", { validation: { min: 0 } }],
  ["orders.return_exchange_window_days", "orders", "number", 14, "Return/exchange window days", "مدة الاسترجاع والاستبدال", "Allowed return and exchange period.", "مدة السماح بالاسترجاع والاستبدال.", { validation: { min: 0 }, isPublic: true, usedBy: ["Storefront Returns Policy", "Merchant Listings"] }],
  ["orders.shipping_provider", "shipping", "select", "in_store_delivery", "Shipping provider", "شركة الشحن", "Default shipping provider.", "شركة الشحن الافتراضية.", { options: [option("bosta", "Bosta", "بوسطة"), option("mylerz", "Mylerz", "مايلرز"), option("shipblu", "ShipBlu", "شيب بلو"), option("in_store_delivery", "In Store Delivery", "توصيل داخلي")], usedBy: ["Orders", "Shipping"] }],
  ["orders.shipment_notifications", "shipping", "json", SHIPMENT_NOTIFICATION_DEFAULTS, "Shipment WhatsApp notifications", "رسائل الشحن على واتساب", "Per-status message templates and on/off switches. Edited from the gear in the Shipping Center.", "قوالب رسائل الشحن وتشغيلها أو إيقافها لكل حالة. تُعدَّل من ترس الإعدادات في مركز الشحن.", { usedBy: ["Shipping", "WhatsApp"] }],
  ["marketing.abandoned_cart_reminder", "ai_channels", "json", ABANDONED_CART_DEFAULTS, "Abandoned cart WhatsApp reminder", "تذكير السلة المتروكة على واتساب", "One carousel per abandonment: the saved cart's products as cards with a complete-order button. enabled / delay_minutes / max_cards / body / button_text.", "رسالة واحدة لكل سلة متروكة: منتجات السلة ككروت مع زر أكمل الطلب. التشغيل، مدة الانتظار بالدقائق، عدد الكروت، نص الرسالة ونص الزر.", { usedBy: ["Marketing", "WhatsApp"] }],
  ["orders.whatsapp_order_confirmation_template", "orders", "textarea", "تم استلام طلبك رقم {{order_number}}.", "WhatsApp order confirmation template", "رسالة تأكيد الطلب واتساب", "Template for order confirmation messages.", "قالب رسالة تأكيد الطلب."],

  // The WhatsApp outbound queue. Nothing here is a number this code claims WhatsApp considers
  // safe — every one of them is the operator's decision, which is exactly why they are settings
  // and not constants in the worker.
  ["whatsapp.queue", "ai_channels", "json", WHATSAPP_QUEUE_DEFAULTS, "WhatsApp outbound queue", "طابور رسائل واتساب", "Paces every automated WhatsApp message instead of posting it straight at the gateway. enabled / messages_per_minute / min_delay_seconds / max_delay_seconds / batch_size, plus the circuit breaker: offline_pause_minutes, pending_pause_threshold, failure_pause_threshold, failure_window_minutes. Off = the previous direct-send behaviour, unchanged.", "ينظّم إرسال كل رسائل واتساب التلقائية بدلاً من إرسالها مباشرة للجهاز. التشغيل، عدد الرسائل في الدقيقة، أقل وأكبر تأخير، حجم الدفعة، بالإضافة لقاطع الأمان: مدة الانقطاع، حد الرسائل المتراكمة، حد الأخطاء ومدة نافذتها. الإيقاف يعيد السلوك القديم كما هو.", { usedBy: ["WhatsApp", "Orders", "Marketing"] }],
  ["whatsapp.queue_categories", "ai_channels", "json", WHATSAPP_QUEUE_CATEGORY_DEFAULTS, "WhatsApp queue category rules", "قواعد فئات طابور واتساب", "Separate expiry, retry and rate rules for transactional messages (order confirmation, status, invoice) and engagement messages (thank you, Google review, offers). expiry_minutes / max_retries / retry_backoff_seconds / messages_per_minute (0 = use the global rate).", "قواعد منفصلة للصلاحية وإعادة المحاولة والمعدل بين الرسائل المعاملاتية (تأكيد الطلب، حالة الطلب، الفاتورة) ورسائل التفاعل (الشكر، تقييم جوجل، العروض). مدة الصلاحية، أقصى إعادة محاولة، مدة الانتظار، وعدد الرسائل في الدقيقة (0 = المعدل العام).", { usedBy: ["WhatsApp"] }],
  ["whatsapp.automation_expiry", "ai_channels", "json", WHATSAPP_AUTOMATION_EXPIRY_DEFAULTS, "WhatsApp message expiry per type", "صلاحية كل نوع رسالة واتساب", "How long each automation may sit unsent before it is dropped instead of delivered late, in minutes. 0 means use the category rule. This is what stops a day-old thank-you or review ask from being sent after the session comes back.", "المدة التي تُسمح فيها كل رسالة بالانتظار قبل أن تُلغى بدل إرسالها متأخرة، بالدقائق. القيمة 0 تعني استخدام قاعدة الفئة. هذه هي القاعدة التي تمنع إرسال رسالة شكر أو طلب تقييم عمرها يوم كامل بعد رجوع الاتصال.", { usedBy: ["WhatsApp"] }],
  ["whatsapp.message_variants", "ai_channels", "json", WHATSAPP_MESSAGE_VARIANT_DEFAULTS, "WhatsApp message variants", "صيغ رسائل واتساب", "More than one wording per automation, used round robin: customer 1 gets A, customer 2 gets B, customer 3 gets C, customer 4 gets A. Every variant supports the same placeholders. Empty = the automation's own message goes out exactly as it does today.", "أكثر من صيغة لكل رسالة تلقائية، تُستخدم بالتناوب: العميل الأول A والثاني B والثالث C والرابع A. كل صيغة تدعم نفس المتغيرات. الفراغ يعني إرسال رسالة النظام الأصلية كما هي.", { usedBy: ["WhatsApp", "Marketing"] }],
  ["orders.bosta_api_base_url", "shipping", "url", "https://app.bosta.co/api/v2", "Bosta API base URL", "Bosta API base URL", "Base URL for Bosta API requests.", "Base URL for Bosta API requests.", { usedBy: ["Shipping"] }],
  ["orders.bosta_api_key", "shipping", "secret", "", "Bosta API key", "مفتاح بوسطة", "Secret key for Bosta shipping.", "مفتاح سري لتكامل بوسطة.", { isSecret: true, usedBy: ["Shipping"] }],
  ["orders.bosta_webhook_secret", "shipping", "secret", "", "Bosta webhook secret", "مفتاح ويبهوك بوسطة", "Shared secret Bosta signs status callbacks with.", "المفتاح الذي توقّع به بوسطة تحديثات حالة الشحنة.", { isSecret: true, usedBy: ["Shipping"] }],
  ["orders.bosta_allow_open_package", "shipping", "select", "inherit", "Bosta open-package policy", "فتح الشحنة عند بوسطة", "Whether the customer may open the parcel before paying. \"Bosta account default\" sends no instruction and leaves your Bosta account setting in charge.", "هل يُسمح للعميل بفتح الشحنة قبل الدفع. اختيار «افتراضي حساب بوسطة» لا يرسل أي تعليمات ويترك إعداد حسابك في بوسطة كما هو.", { options: [option("inherit", "Bosta account default", "افتراضي حساب بوسطة"), option("allow", "Allow opening", "السماح بالفتح"), option("deny", "Do not allow opening", "عدم السماح بالفتح")], usedBy: ["Shipping", "Orders"] }],

  ["storefront.enabled", "storefront", "boolean", true, "Storefront enabled", "تفعيل المتجر", "Enable public storefront routes.", "تفعيل صفحات المتجر العامة.", { isPublic: true }],
  ["storefront.public_url", "storefront", "url", "", "Public store URL", "رابط المتجر", "Base public URL for sharing product and order links.", "الرابط العام لمشاركة المنتجات والطلبات.", { isPublic: true, usedBy: ["Storefront", "AI"] }],
  ["storefront.store_name", "storefront", "text", "", "Store name", "اسم المتجر", "Public store display name.", "اسم المتجر الظاهر للعملاء.", { isPublic: true }],
  ["storefront.store_logo_url", "storefront", "url", "", "Store logo", "شعار المتجر", "Public store logo URL.", "رابط شعار المتجر.", { isPublic: true }],
  ["storefront.header_logo_url", "storefront", "url", "", "Header wordmark", "الشعار الأفقي للهيدر", "Transparent horizontal logo used only in the storefront header.", "شعار أفقي بخلفية شفافة يُستخدم في هيدر المتجر فقط.", { isPublic: true }],
  ["storefront.store_tagline", "storefront", "text", "", "Store tagline", "شعار المتجر النصي", "Short tagline shown beneath the store name on the storefront header.", "عبارة قصيرة تظهر أسفل اسم المتجر في رأس المتجر.", { isPublic: true, validation: { maxLength: 120 } }],
  ["storefront.favicon_url", "storefront", "url", "", "Favicon", "أيقونة المتجر", "Public browser favicon URL.", "رابط أيقونة المتجر في المتصفح.", { isPublic: true }],
  ["storefront.contact_phone", "storefront", "text", "", "Contact phone", "رقم الهاتف", "Primary public contact phone shown to customers.", "رقم الهاتف الأساسي الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 64 } }],
  ["storefront.whatsapp_phone", "storefront", "text", "", "WhatsApp phone", "رقم واتساب", "WhatsApp phone number shown to customers.", "رقم واتساب الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 64 } }],
  ["storefront.whatsapp_url", "storefront", "url", "", "WhatsApp direct URL", "رابط واتساب مباشر", "Direct WhatsApp URL used when provided.", "رابط واتساب مباشر يستخدم عند توفره.", { isPublic: true, validation: { maxLength: 2048 } }],
  ["storefront.instagram_username", "storefront", "text", "", "Instagram username", "اسم حساب انستجرام", "Instagram handle shown to customers.", "اسم حساب انستجرام الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 80 } }],
  ["storefront.instagram_url", "storefront", "url", "", "Instagram URL", "رابط انستجرام", "Direct Instagram profile URL.", "رابط صفحة انستجرام المباشر.", { isPublic: true, validation: { maxLength: 2048 } }],
  ["storefront.facebook_page_name", "storefront", "text", "", "Facebook page name", "اسم صفحة فيسبوك", "Facebook page name shown to customers.", "اسم صفحة فيسبوك الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 120 } }],
  ["storefront.facebook_url", "storefront", "url", "", "Facebook URL", "رابط فيسبوك", "Direct Facebook page URL.", "رابط صفحة فيسبوك المباشر.", { isPublic: true, validation: { maxLength: 2048 } }],
  ["storefront.address", "storefront", "textarea", "", "Store address", "عنوان المتجر", "Public store address shown on the contact page.", "عنوان المتجر الظاهر في صفحة التواصل.", { isPublic: true, validation: { maxLength: 500 } }],
  ["storefront.map_url", "storefront", "url", "", "Map URL", "رابط الخريطة", "Google Maps or other map URL for the store.", "رابط الخريطة أو Google Maps الخاص بالمتجر.", { isPublic: true, validation: { maxLength: 2048 } }],
  ["storefront.working_hours", "storefront", "textarea", "", "Working hours", "مواعيد العمل", "Public working hours text shown to customers.", "نص مواعيد العمل الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 500 } }],
  ["storefront.homepage_hero", "storefront", "json", { title: "", subtitle: "", imageUrl: "" }, "Homepage hero settings", "واجهة الصفحة الرئيسية", "Hero title, subtitle, and image URL.", "العنوان والوصف وصورة واجهة الصفحة الرئيسية.", { isPublic: true }],
  ["storefront.featured_collections", "storefront", "json", [], "Featured collections", "المجموعات المميزة", "Collection IDs or slugs displayed on home.", "معرفات أو روابط المجموعات الظاهرة في الرئيسية.", { isPublic: true }],
  ["storefront.default_shipping_price", "shipping", "number", 60, "Default shipping price", "سعر الشحن الافتراضي", "Fallback shipping price when no governorate, city, or area zone matches.", "سعر الشحن الاحتياطي عند عدم وجود منطقة أو مدينة أو محافظة مطابقة.", { validation: { min: 0 }, usedBy: ["Storefront", "Checkout"] }],
  ["storefront.shipping_handling_min_days", "shipping", "number", 0, "Minimum order handling days", "الحد الأدنى لمدة تجهيز الطلب", "Time from order registration until handoff to the shipping company. It does not include customer transit time.", "المدة من تسجيل الطلب حتى تسليمه لشركة الشحن، ولا تشمل مدة النقل للعميل.", { validation: { min: 0, integer: true }, usedBy: ["Storefront Product Schema", "Merchant Shipping"] }],
  ["storefront.shipping_handling_max_days", "shipping", "number", 1, "Maximum order handling days", "الحد الأقصى لمدة تجهيز الطلب", "Time from order registration until handoff to the shipping company. It does not include customer transit time.", "المدة من تسجيل الطلب حتى تسليمه لشركة الشحن، ولا تشمل مدة النقل للعميل.", { validation: { min: 0, integer: true }, usedBy: ["Storefront Product Schema", "Merchant Shipping"] }],
  ["storefront.shipping_locations", "shipping", "json", defaultEgyptShippingLocations, "Shipping locations catalog", "كتالوج مناطق الشحن", "Structured Egypt governorate, city/markaz, and area catalog used by zones and checkout.", "كتالوج منظم لمحافظات ومدن ومناطق مصر مستخدم في مناطق الشحن والدفع.", { isPublic: true, usedBy: ["Shipping Zones", "Storefront Checkout"] }],
  ["storefront.shipping_zones", "shipping", "json", defaultStorefrontShippingZones, "Shipping zones", "مناطق الشحن", "Governorate, city, and optional area shipping prices used by checkout.", "أسعار الشحن حسب المحافظة والمدينة والمنطقة المستخدمة في الدفع.", { usedBy: ["Storefront", "Checkout"] }],
  ["storefront.return_policy_enabled", "storefront", "boolean", true, "Return policy enabled", "تفعيل سياسة الاستبدال والاسترجاع", "Publish the configured return policy on the storefront and merchant listings.", "نشر سياسة الاستبدال والاسترجاع في المتجر وبيانات Merchant Listings.", { isPublic: true, usedBy: ["Storefront Returns Policy", "Merchant Listings"] }],
  ["storefront.return_method", "storefront", "select", "mail", "Return method", "طريقة رد المنتج", "General method customers use to send returned products.", "الطريقة العامة التي يستخدمها العميل لإرسال المنتج المرتجع.", { isPublic: true, options: [option("mail", "Shipping carrier", "شركة الشحن"), option("in_store", "Return in store", "الاسترجاع داخل المتجر")], usedBy: ["Storefront Returns Policy", "Merchant Listings"] }],
  ["storefront.customer_remorse_return_fees", "storefront", "select", "customer_responsibility", "Customer-choice return fees", "تكلفة الاسترجاع بسبب اختيار العميل", "Who pays return shipping when the customer chose the wrong size, color, or model.", "من يتحمل الشحن عند اختيار العميل مقاسًا أو لونًا أو موديلًا غير مناسب.", { isPublic: true, options: [option("customer_responsibility", "Customer responsibility", "على العميل"), option("free", "Merchant responsibility", "على المتجر")], usedBy: ["Storefront Returns Policy", "Merchant Listings"] }],
  ["storefront.defect_return_fees", "storefront", "select", "merchant_responsibility", "Defect or store-error return fees", "تكلفة الاسترجاع عند العيب أو خطأ المتجر", "Who pays shipping for a confirmed defect or store fulfillment error.", "من يتحمل الشحن عند وجود عيب مؤكد أو خطأ في تجهيز الطلب.", { isPublic: true, options: [option("merchant_responsibility", "Merchant responsibility", "على المتجر"), option("customer_responsibility", "Customer responsibility", "على العميل")], usedBy: ["Storefront Returns Policy"] }],
  ["storefront.return_policy_url", "storefront", "text", "https://m1store-egy.com/returns", "Public return policy URL", "رابط سياسة الاستبدال والاسترجاع", "Canonical public URL for the complete return policy.", "الرابط العام المعتمد لصفحة سياسة الاستبدال والاسترجاع.", { isPublic: true, validation: { maxLength: 300 }, usedBy: ["Merchant Listings"] }],
  ["storefront.return_policy_conditions", "storefront", "json", {
    unused_original_condition: "المنتج غير مستخدم وبحالته الأصلية ومع العبوة والملحقات.",
    invoice_required: "يجب تقديم الفاتورة أو رقم الطلب.",
    customer_choice_shipping: "عند خطأ المقاس أو تغيير اللون أو الموديل من العميل يتحمل العميل تكلفة الشحن ذهابًا وإيابًا.",
    defect_shipping: "عند وجود عيب مؤكد أو خطأ من المتجر يتحمل المتجر تكلفة الشحن بالكامل."
  }, "Return policy conditions", "شروط سياسة الاستبدال والاسترجاع", "Structured public wording shared by the return policy page and merchant data.", "نصوص منظمة مشتركة بين صفحة السياسة وبيانات التجارة.", { isPublic: true, usedBy: ["Storefront Returns Policy"] }],
  ["storefront.payment_methods.vodafone_cash_enabled", "storefront", "boolean", true, "Vodafone Cash enabled", "تفعيل فودافون كاش", "Show Vodafone Cash as a customer payment option.", "إظهار فودافون كاش كخيار دفع للعملاء.", { isPublic: true }],
  ["storefront.payment_methods.vodafone_cash_display_name", "storefront", "text", "Vodafone Cash", "Vodafone Cash display name", "اسم العرض لفودافون كاش", "Public label shown to customers.", "الاسم الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 80 } }],
  ["storefront.payment_methods.vodafone_cash_number", "storefront", "text", "01000000000", "Vodafone Cash wallet number", "رقم محفظة فودافون كاش", "Wallet number shown to customers.", "رقم المحفظة الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 64 } }],
  ["storefront.payment_methods.vodafone_cash_logo_url", "storefront", "url", "", "Vodafone Cash logo", "شعار فودافون كاش", "Optional logo shown in checkout.", "شعار اختياري يظهر في صفحة الدفع.", { isPublic: true }],
  ["storefront.payment_methods.vodafone_cash_helper_text", "storefront", "textarea", "", "Vodafone Cash helper text", "نص مساعد لفودافون كاش", "Helper text shown below the payment details.", "نص إرشادي يظهر أسفل تفاصيل الدفع.", { isPublic: true }],
  ["storefront.payment_methods.instapay_enabled", "storefront", "boolean", true, "Instapay enabled", "تفعيل إنستاباي", "Show Instapay as a customer payment option.", "إظهار إنستاباي كخيار دفع للعملاء.", { isPublic: true }],
  ["storefront.payment_methods.instapay_display_name", "storefront", "text", "InstaPay", "Instapay display name", "اسم العرض لإنستاباي", "Public label shown to customers.", "الاسم الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 80 } }],
  ["storefront.payment_methods.instapay.payment_url", "storefront", "url", "https://ipn.eg/S/maged.helal/instapay/5BEvfH", "Instapay payment URL", "رابط الدفع لإنستاباي", "Direct payment link shown to customers in checkout.", "رابط الدفع المباشر الظاهر للعملاء في صفحة الدفع.", { isPublic: true, validation: { maxLength: 2048 } }],
  ["storefront.payment_methods.instapay_handle", "storefront", "text", "01000000000@instapay", "Instapay handle / phone", "حساب أو رقم إنستاباي", "Handle or phone shown to customers.", "الحساب أو الرقم الظاهر للعملاء.", { isPublic: true, validation: { maxLength: 64 } }],
  ["storefront.payment_methods.instapay_logo_url", "storefront", "url", "", "Instapay logo", "شعار إنستاباي", "Optional logo shown in checkout.", "شعار اختياري يظهر في صفحة الدفع.", { isPublic: true }],
  ["storefront.payment_methods.instapay_helper_text", "storefront", "textarea", "", "Instapay helper text", "نص مساعد لإنستاباي", "Helper text shown below the payment details.", "نص إرشادي يظهر أسفل تفاصيل الدفع.", { isPublic: true }],
  ["storefront.payment_methods.shipping_confirmation_enabled", "storefront", "boolean", true, "Shipping confirmation enabled", "تفعيل رسوم تأكيد الشحن", "Show the shipping confirmation amount card in checkout.", "إظهار بطاقة رسوم تأكيد الشحن في صفحة الدفع.", { isPublic: true }],
  ["storefront.payment_methods.shipping_confirmation_amount", "storefront", "number", 75, "Shipping confirmation amount", "قيمة تأكيد الشحن", "Amount shown for shipping confirmation in checkout.", "المبلغ الظاهر لتأكيد الشحن في صفحة الدفع.", { isPublic: true, validation: { min: 0, max: 100000 } }],
  ["storefront.payment_methods.shipping_confirmation_label", "storefront", "text", "رسوم تأكيد الطلب", "Shipping confirmation label", "نص رسوم تأكيد الشحن", "Label shown above the configured amount.", "العنوان الظاهر أعلى المبلغ المحدد.", { isPublic: true, validation: { maxLength: 120 } }],
  ["storefront.product_sorting_default", "storefront", "select", "newest", "Default product sorting", "ترتيب المنتجات", "Default catalog sorting.", "ترتيب المنتجات الافتراضي.", { options: [option("newest", "Newest", "الأحدث"), option("price_asc", "Price low to high", "السعر من الأقل"), option("price_desc", "Price high to low", "السعر من الأعلى"), option("popular", "Popular", "الأكثر مشاهدة")], isPublic: true }],
  ["storefront.show_sold_out_products", "storefront", "boolean", true, "Show sold out products", "إظهار غير المتوفر", "Display out-of-stock products.", "عرض المنتجات غير المتوفرة.", { isPublic: true }],
  ["storefront.show_low_stock_badge", "storefront", "boolean", true, "Show low stock badge", "إظهار قرب النفاد", "Show low stock label to customers.", "عرض علامة قرب النفاد للعملاء.", { isPublic: true }],
  ["storefront.show_product_views", "storefront", "boolean", false, "Show product views", "إظهار مشاهدات المنتج", "Display product views publicly.", "عرض عدد المشاهدات للعملاء.", { isPublic: true }],
  ["storefront.enable_wishlist", "storefront", "boolean", true, "Enable wishlist", "تفعيل المفضلة", "Allow customers to save products.", "السماح للعملاء بحفظ المنتجات.", { isPublic: true }],
  ["storefront.enable_product_sharing", "storefront", "boolean", true, "Enable product sharing", "تفعيل مشاركة المنتج", "Show share controls on products.", "عرض أزرار مشاركة المنتجات.", { isPublic: true }],
  ["storefront.enable_size_guide", "storefront", "boolean", true, "Enable size guide", "تفعيل دليل المقاسات", "Show size guide links.", "إظهار روابط دليل المقاسات.", { isPublic: true }],
  ["storefront.seo_title", "storefront", "text", "", "SEO title", "عنوان SEO", "Default SEO title for storefront.", "عنوان SEO الافتراضي للمتجر.", { isPublic: true }],
  ["storefront.seo_description", "storefront", "textarea", "", "SEO description", "وصف SEO", "Default SEO description.", "وصف SEO الافتراضي.", { isPublic: true }],
  ["storefront.open_graph_image_url", "storefront", "url", "", "Open Graph image", "صورة المشاركة", "Default image used when the store is shared.", "الصورة الافتراضية عند مشاركة المتجر.", { isPublic: true }],
  ["storefront.meta_pixel_id", "storefront", "text", "", "Meta Pixel ID", "معرف Meta Pixel", "Placeholder for Meta Pixel.", "عنصر جاهز لتكامل Meta Pixel.", { placeholder: true }],
  ["storefront.facebook_catalog_id", "storefront", "text", "", "Facebook Catalog ID", "معرف كتالوج فيسبوك", "Placeholder for Facebook Catalog sync.", "عنصر جاهز لمزامنة كتالوج فيسبوك.", { placeholder: true }],
  ["storefront.tiktok_pixel_id", "storefront", "text", "", "TikTok Pixel ID", "معرف TikTok Pixel", "Placeholder for TikTok Pixel.", "عنصر جاهز لتكامل TikTok Pixel.", { placeholder: true, isPublic: true }],
  ["storefront.google_analytics_id", "storefront", "text", "", "Google Analytics ID", "معرف Google Analytics", "Placeholder for Google Analytics.", "عنصر جاهز لتكامل Google Analytics.", { placeholder: true, isPublic: true }],

  ["pos.default_branch_id", "pos", "text", "", "Default branch", "الفرع الافتراضي", "POS branch fallback.", "فرع نقطة البيع الافتراضي."],
  ["pos.default_warehouse_id", "pos", "text", "", "Default warehouse", "المخزن الافتراضي", "POS stock warehouse fallback.", "مخزن نقطة البيع الافتراضي."],
  ["pos.default_cashier_treasury_id", "pos", "text", "", "Default cashier treasury", "خزينة الكاشير", "Default treasury for cash sales.", "الخزينة الافتراضية للمبيعات النقدية."],
  ["pos.allow_discount", "pos", "boolean", true, "Allow discount", "السماح بالخصم", "Allow POS line/order discounts.", "السماح بخصومات نقطة البيع."],
  ["pos.max_discount_percent", "pos", "number", 20, "Max discount percent", "أقصى نسبة خصم", "Maximum discount without override.", "أقصى خصم بدون موافقة.", { validation: { min: 0, max: 100 } }],
  ["pos.manager_approval_discount_percent", "pos", "number", 10, "Manager approval above discount %", "موافقة المدير فوق نسبة خصم", "Require manager approval above this discount.", "تتطلب موافقة المدير فوق هذه النسبة.", { validation: { min: 0, max: 100 } }],
  ["pos.allow_split_payments", "pos", "boolean", true, "Allow split payments", "تقسيم الدفع", "Allow multiple payment methods.", "السماح بأكثر من وسيلة دفع."],
  ["pos.allow_customer_credit", "pos", "boolean", false, "Allow customer credit", "السماح بمديونية العميل", "Allow sale on customer credit.", "السماح بالبيع على حساب العميل."],
  ["pos.allow_returns", "pos", "boolean", true, "Allow returns", "السماح بالمرتجعات", "Allow POS returns.", "السماح بمرتجعات نقطة البيع."],
  ["pos.print_receipt_automatically", "pos", "boolean", false, "Automatically print the receipt after completing the sale", "الطباعة التلقائية للفاتورة بعد إتمام البيع", "Print immediately through the configured thermal printer after checkout. Silent output requires a native print bridge or browser kiosk-printing mode.", "إرسال الفاتورة مباشرة إلى الطابعة الحرارية بعد إتمام البيع. تتطلب الطباعة بلا نافذة قناة طباعة محلية أو تشغيل المتصفح بوضع الطباعة الصامتة."],
  ["pos.auto_send_pos_invoice_whatsapp", "pos", "boolean", true, "Auto send WhatsApp invoice after checkout", "إرسال فاتورة واتساب تلقائيا بعد البيع", "Automatically send the public invoice link by WhatsApp after POS checkout.", "إرسال رابط الفاتورة العام عبر واتساب تلقائيا بعد إتمام بيع نقطة البيع."],
  ["pos.receipt_template", "pos", "select", "compact", "Receipt template", "قالب الإيصال", "Receipt layout.", "شكل الإيصال.", { options: [option("compact", "Compact", "مختصر"), option("detailed", "Detailed", "تفصيلي")] }],
  ["pos.barcode_scanner_behavior", "pos", "select", "add_to_cart", "Barcode scanner behavior", "سلوك قارئ الباركود", "What happens after scanning a barcode.", "ما يحدث بعد قراءة الباركود.", { options: [option("add_to_cart", "Add to cart", "إضافة للسلة"), option("open_product", "Open product", "فتح المنتج")] }],
  ["pos.hold_cart_timeout_minutes", "pos", "number", 120, "Hold cart timeout", "مدة تعليق السلة", "Minutes before held carts expire.", "الدقائق قبل انتهاء السلة المعلقة.", { validation: { min: 0 } }],

  ["inventory.default_warehouse_id", "inventory", "text", "", "Default warehouse", "المخزن الافتراضي", "Default inventory warehouse.", "المخزن الافتراضي للمخزون."],
  ["inventory.low_stock_threshold", "inventory", "number", 5, "Low stock threshold", "حد المخزون المنخفض", "Default low stock alert threshold.", "حد تنبيه المخزون المنخفض.", { validation: { min: 0 } }],
  ["inventory.auto_generate_sku", "inventory", "boolean", true, "Auto-generate SKU", "إنشاء SKU تلقائيا", "Generate SKU for new products.", "إنشاء كود SKU للمنتجات الجديدة."],
  ["inventory.sku_pattern", "inventory", "text", "SKU-{category}-{seq}", "SKU pattern", "نمط SKU", "Pattern used for SKU generation.", "النمط المستخدم لإنشاء SKU."],
  ["inventory.allow_negative_stock", "inventory", "boolean", false, "Allow negative stock", "السماح بالمخزون السالب", "Should remain off unless explicitly needed.", "يفضل أن يظل مغلقا إلا عند الحاجة."],
  ["inventory.reserve_stock_behavior", "inventory", "select", "on_order", "Reserve stock behavior", "طريقة حجز المخزون", "When stock is reserved.", "متى يتم حجز المخزون.", { options: [option("off", "Off", "إيقاف"), option("on_order", "On order", "عند الطلب"), option("on_payment", "On payment", "عند الدفع")] }],
  ["inventory.stock_transfer_approval_required", "inventory", "boolean", true, "Stock transfer approval required", "موافقة على تحويل المخزون", "Require approval before transfer completion.", "تتطلب موافقة قبل إتمام التحويل."],
  ["inventory.purchase_receiving_behavior", "inventory", "select", "receive_to_default", "Purchase receiving behavior", "استلام المشتريات", "Default receiving destination.", "وجهة الاستلام الافتراضية.", { options: [option("receive_to_default", "Default warehouse", "المخزن الافتراضي"), option("ask_each_time", "Ask each time", "اسأل كل مرة")] }],
  ["inventory.product_image_source_priority", "inventory", "select", "variant_first", "Product image source priority", "أولوية صورة المنتج", "Which image is preferred in catalog.", "الصورة المفضلة في الكتالوج.", { options: [option("variant_first", "Variant first", "المتغير أولا"), option("product_first", "Product first", "المنتج أولا")] }],
  ["inventory.variant_naming_format", "inventory", "text", "{product} - {color} - {size}", "Variant naming format", "تنسيق اسم المتغير", "Format for displayed variant names.", "تنسيق عرض أسماء المتغيرات."],

  ["accounting.default_cash_account_id", "accounting", "text", "", "Default cash account", "حساب النقدية", "Default ledger cash account.", "حساب النقدية الافتراضي."],
  ["accounting.default_bank_account_id", "accounting", "text", "", "Default bank account", "حساب البنك", "Default ledger bank account.", "حساب البنك الافتراضي."],
  ["accounting.default_sales_revenue_account_id", "accounting", "text", "", "Default sales revenue account", "حساب إيراد المبيعات", "Revenue account for sales posting.", "حساب إيرادات المبيعات."],
  ["accounting.default_shipping_income_account_id", "accounting", "text", "", "Default shipping income account", "حساب دخل الشحن", "Income account for collected shipping.", "حساب دخل الشحن المحصل."],
  ["accounting.default_shipping_expense_account_id", "accounting", "text", "", "Default shipping expense account", "حساب مصروف الشحن", "Expense account for carrier fees.", "حساب مصروف شركة الشحن."],
  ["accounting.default_cogs_account_id", "accounting", "text", "", "Default COGS account", "حساب تكلفة البضاعة", "Cost of goods sold account.", "حساب تكلفة البضاعة المباعة."],
  ["accounting.default_inventory_asset_account_id", "accounting", "text", "", "Default inventory asset account", "حساب أصل المخزون", "Inventory asset account.", "حساب أصل المخزون."],
  ["accounting.default_customer_credit_account_id", "accounting", "text", "", "Default customer credit account", "حساب مديونية العملاء", "Customer receivable/credit account.", "حساب ذمم العملاء."],
  ["accounting.default_supplier_payable_account_id", "accounting", "text", "", "Default supplier payable account", "حساب الموردين", "Supplier payable account.", "حساب ذمم الموردين."],
  ["accounting.auto_post_pos_sales", "accounting", "boolean", false, "Auto-post POS sales", "ترحيل مبيعات الكاشير تلقائيا", "Create accounting entries for POS sales.", "إنشاء قيود محاسبية لمبيعات الكاشير."],
  ["accounting.auto_post_website_orders", "accounting", "boolean", false, "Auto-post website orders", "ترحيل طلبات الموقع تلقائيا", "Create entries for website orders.", "إنشاء قيود لطلبات الموقع."],
  ["accounting.auto_post_expenses", "accounting", "boolean", false, "Auto-post expenses", "ترحيل المصروفات تلقائيا", "Create entries when expenses are approved.", "إنشاء قيود عند اعتماد المصروفات."],
  ["accounting.vat_enabled", "accounting", "boolean", false, "Tax/VAT enabled", "تفعيل الضريبة", "Enable tax/VAT calculations.", "تفعيل حسابات الضريبة."],
  ["accounting.vat_rate_percent", "accounting", "number", 14, "VAT rate percent", "نسبة الضريبة", "Default VAT percent.", "نسبة الضريبة الافتراضية.", { validation: { min: 0, max: 100 } }],

  ["employees.default_attendance_timezone", "employees", "select", "Africa/Cairo", "Default attendance timezone", "منطقة الحضور الزمنية", "Decides when the attendance day starts and ends, and anchors shift, late and overtime calculations.", "تحدد بداية ونهاية يوم الحضور، وعليها يُحسب الشيفت والتأخير والإضافي.", { options: attendanceTimeZoneOptions }],
  ["employees.default_shift_behavior", "employees", "select", "scheduled", "Default shift behavior", "نظام الشفت الافتراضي", "How missing shifts are handled.", "طريقة التعامل مع الشفتات غير المحددة.", { options: [option("scheduled", "Scheduled", "حسب الجدول"), option("flexible", "Flexible", "مرن")] }],
  ["employees.grace_period_minutes", "employees", "number", 10, "Grace period minutes", "دقائق السماح", "Late grace period.", "فترة السماح للتأخير.", { validation: { min: 0 } }],
  ["employees.late_deduction_rules", "employees", "json", [], "Late deduction rules", "قواعد خصم التأخير", "JSON rules for late deductions.", "قواعد JSON لخصم التأخير."],
  ["employees.overtime_rules", "employees", "json", [], "Overtime rules", "قواعد الإضافي", "JSON rules for overtime.", "قواعد JSON للإضافي."],
  ["employees.payroll_cycle", "employees", "select", "monthly", "Payroll cycle", "دورة المرتبات", "Payroll calculation period.", "فترة حساب المرتبات.", { options: [option("monthly", "Monthly", "شهري"), option("weekly", "Weekly", "أسبوعي")] }],
  ["employees.commission_calculation_mode", "employees", "select", "paid_orders", "Commission calculation mode", "طريقة حساب العمولة", "Which sales count toward commissions.", "ما هي المبيعات التي تدخل في العمولة.", { options: [option("paid_orders", "Paid orders", "الطلبات المدفوعة"), option("completed_orders", "Completed orders", "الطلبات المكتملة")] }],
  ["employees.advances_deduction_behavior", "employees", "select", "current_cycle", "Advances deduction behavior", "خصم السلف", "How advances are deducted from payroll.", "طريقة خصم السلف من المرتب.", { options: [option("current_cycle", "Current cycle", "الدورة الحالية"), option("manual", "Manual", "يدوي")] }],
  ["employees.portal_enabled", "employees", "boolean", true, "Employee portal enabled", "تفعيل بوابة الموظف", "Allow employee wallet public-token access.", "السماح بدخول محفظة الموظف بالرابط العام."],
  ["employees.qr_attendance_enabled", "employees", "boolean", true, "QR attendance enabled", "تفعيل حضور QR", "Allow QR attendance from employee wallet.", "السماح بالحضور من محفظة الموظف عبر QR."],
  ["employees.qr_expiry_minutes", "employees", "number", 15, "QR expiry minutes", "انتهاء QR بالدقائق", "Branch QR token expiry duration.", "مدة انتهاء رمز QR للفرع.", { validation: { min: 1 } }],

  ["ai_channels.ai_support_enabled", "ai_channels", "boolean", true, "AI Support enabled", "تفعيل دعم الذكاء", "Enable AI-assisted support features.", "تفعيل ميزات دعم الذكاء."],
  ["ai_channels.openai_agent_api_key", "ai_channels", "secret", "", "OpenAI Agent API key", "مفتاح OpenAI للمساعد", "Used only by the AI agent, customer replies, and image understanding.", "يُستخدم فقط بواسطة مساعد الذكاء وردود العملاء وفهم الصور.", { isSecret: true, validation: { maxLength: 500 } }],
  ["ai_channels.openai_thermal_api_key", "ai_channels", "secret", "", "OpenAI Thermal API key", "مفتاح OpenAI للصور الثرمال", "Used only to generate thermal artwork and product image assets.", "يُستخدم فقط لإنشاء صور الثرمال وتصميمات صور المنتجات.", { isSecret: true, validation: { maxLength: 500 } }],
  ["ai_channels.ai_reply_mode", "ai_channels", "select", "suggest_only", "AI reply mode", "وضع رد الذكاء", "Controls how AI replies are used.", "يتحكم في استخدام ردود الذكاء.", { options: [option("off", "Off", "إيقاف"), option("suggest_only", "Suggest only", "اقتراح فقط"), option("auto_reply_after_approval", "Auto after approval", "تلقائي بعد الموافقة"), option("fully_automatic", "Fully automatic", "تلقائي كامل")] }],
  ["ai_channels.human_takeover_behavior", "ai_channels", "select", "pause_ai", "Human takeover behavior", "سلوك تدخل الموظف", "What AI does after a human joins.", "ما يفعله الذكاء بعد تدخل موظف.", { options: [option("pause_ai", "Pause AI", "إيقاف الذكاء"), option("suggest_only", "Suggest only", "اقتراح فقط")] }],
  ["ai_channels.auto_return_to_ai_minutes", "ai_channels", "number", 60, "Auto-return to AI minutes", "العودة للذكاء بعد دقائق", "Return conversation to AI after inactivity.", "إعادة المحادثة للذكاء بعد عدم النشاط.", { validation: { min: 0 } }],
  ["ai_channels.product_recommendation_strictness", "ai_channels", "select", "stock_only", "Product recommendation strictness", "دقة اقتراح المنتجات", "Limits AI recommendations to valid products.", "تقييد اقتراحات الذكاء على منتجات صالحة.", { options: [option("stock_only", "In-stock only", "المتوفر فقط"), option("catalog_only", "Catalog only", "الكتالوج فقط"), option("relaxed", "Relaxed", "مرن")] }],
  ["ai_channels.allowed_channels", "ai_channels", "multiselect", ["messenger", "instagram"], "Allowed channels", "القنوات المسموحة", "Channels AI can serve.", "القنوات التي يخدمها الذكاء.", { options: [option("messenger", "Messenger", "ماسنجر"), option("instagram", "Instagram", "إنستجرام"), option("whatsapp", "WhatsApp placeholder", "واتساب لاحقا")], placeholder: true }],
  ["ai_channels.meta_integration_enabled", "ai_channels", "boolean", false, "Meta integration enabled", "تفعيل Meta", "Controls Meta channel integration.", "يتحكم في تكامل قنوات Meta."],
  ["ai_channels.webhook_url_display", "ai_channels", "text", "", "Webhook URL display", "رابط Webhook", "Read-only display value for webhook setup.", "قيمة عرض لاستخدامها في إعداد webhook."],
  ["ai_channels.storefront_product_link_base", "ai_channels", "url", "", "Storefront product link base", "رابط منتجات المتجر", "Base URL used in AI product replies.", "الرابط الأساسي لمنتجات المتجر في ردود الذكاء."],
  ["ai_channels.cloudinary_cloud_name", "ai_channels", "text", "", "Cloudinary cloud name", "اسم Cloudinary", "Media cloud setting.", "إعداد وسائط Cloudinary."],
  ["ai_channels.cloudinary_api_secret", "ai_channels", "secret", "", "Cloudinary API secret", "سر Cloudinary", "Secret media integration value.", "قيمة سرية لتكامل الوسائط.", { isSecret: true }],
  ["ai_channels.ai_fallback_message", "ai_channels", "textarea", "سيتم تحويلك لفريق الدعم.", "AI fallback message", "رسالة تعذر الرد", "Shown when AI cannot answer.", "تظهر عند عدم قدرة الذكاء على الرد."],
  ["ai_channels.handoff_message", "ai_channels", "textarea", "سيتم تحويل المحادثة لموظف.", "Handoff message", "رسالة التحويل", "Shown when handing off to a human.", "تظهر عند تحويل المحادثة لموظف."],

  ["notifications.low_stock_alerts", "notifications", "boolean", true, "Low stock alerts", "تنبيهات المخزون المنخفض", "Notify when stock is low.", "تنبيه عند انخفاض المخزون."],
  ["notifications.new_order_alerts", "notifications", "boolean", true, "New order alerts", "تنبيهات الطلبات الجديدة", "Notify admins about new orders.", "تنبيه الإدارة بالطلبات الجديدة."],
  ["notifications.payment_alerts", "notifications", "boolean", true, "Payment alerts", "تنبيهات الدفع", "Notify on payment changes.", "تنبيه عند تغير حالة الدفع."],
  ["notifications.employee_request_alerts", "notifications", "boolean", true, "Employee request alerts", "تنبيهات طلبات الموظفين", "Notify admins about employee wallet requests.", "تنبيه الإدارة بطلبات محفظة الموظف."],
  ["notifications.ai_hot_lead_alerts", "notifications", "boolean", true, "AI hot lead alerts", "تنبيهات العملاء المهمين", "Notify when AI detects a hot lead.", "تنبيه عند اكتشاف عميل مهم."],
  ["notifications.admin_inbox_alerts", "notifications", "boolean", true, "Admin inbox alerts", "تنبيهات صندوق الإدارة", "Notify admin inbox events.", "تنبيه أحداث صندوق الإدارة."],
  ["notifications.channels", "notifications", "multiselect", ["in_app"], "Notification channels", "قنوات الإشعارات", "Enabled delivery channels.", "قنوات إرسال الإشعارات.", { options: [option("in_app", "In-app", "داخل النظام"), option("email", "Email placeholder", "البريد لاحقا"), option("whatsapp", "WhatsApp placeholder", "واتساب لاحقا")], placeholder: true }],

  ["security.roles_permissions_shortcut", "security", "text", "/settings/permissions", "Roles and permissions shortcut", "اختصار الصلاحيات", "Shortcut route for roles and permissions.", "مسار مختصر للصلاحيات."],
  ["security.session_timeout_minutes", "security", "number", 480, "Session timeout minutes", "مدة الجلسة بالدقائق", "Session expiry duration.", "مدة انتهاء الجلسة.", { validation: { min: 5 } }],
  ["security.require_strong_password", "security", "boolean", true, "Require strong password", "طلب كلمة مرور قوية", "Enforce stronger user passwords.", "فرض كلمات مرور أقوى."],
  ["security.two_factor_enabled", "security", "boolean", false, "Two-factor placeholder", "التحقق الثنائي لاحقا", "Placeholder for future two-factor authentication.", "عنصر جاهز للتحقق الثنائي لاحقا.", { placeholder: true }],
  ["security.audit_log_enabled", "security", "boolean", true, "Audit log enabled", "تفعيل سجل التدقيق", "Record sensitive admin activity.", "تسجيل نشاط الإدارة الحساس."],
  ["security.sensitive_settings_require_admin_password", "security", "boolean", true, "Sensitive settings require admin password", "كلمة مرور للإعدادات الحساسة", "Require admin password before changing sensitive values.", "طلب كلمة مرور المدير قبل تغيير القيم الحساسة."],
  ["security.api_tokens_management", "security", "json", [], "API tokens management placeholder", "مفاتيح API لاحقا", "Placeholder for API token management.", "عنصر جاهز لإدارة مفاتيح API لاحقا.", { placeholder: true, isSecret: true }],
];

export const settingsRegistry = definitions.map(([key, category, type, defaultValue, en, ar, descriptionEn, descriptionAr, extra = {}]) => ({
  key,
  category: String(key || "").startsWith("general.barcode_print_") ? "barcode_printing" : category,
  label: label(en, ar),
  description: label(descriptionEn, descriptionAr),
  type,
  defaultValue,
  isSecret: Boolean(extra.isSecret),
  isPublic: Boolean(extra.isPublic),
  validation: extra.validation || {},
  usedBy: extra.usedBy || [],
  options: extra.options || [],
  placeholder: Boolean(extra.placeholder),
}));

export const settingsByKey = settingsRegistry.reduce((acc, setting) => {
  acc[setting.key] = setting;
  return acc;
}, {});

export const settingsByCategory = settingsRegistry.reduce((acc, setting) => {
  if (!acc[setting.category]) acc[setting.category] = [];
  acc[setting.category].push(setting);
  return acc;
}, {});

export const normalizeSettingsCategory = (category) => {
  const value = String(category || "").trim().toLowerCase().replace(/[^a-z0-9_]/g, "_");
  const aliases = {
    company: "general",
    currency: "general",
    currencies: "general",
    localization: "general",
    site: "general",
    website: "storefront",
    store: "storefront",
    shop: "storefront",
    shipping_rules: "shipping",
    fulfillment: "shipping",
    payment: "payments",
    payment_settings: "payments",
    ai: "ai_channels",
    ai_marketing: "ai_channels",
    marketing_ai: "ai_channels",
    ai_settings: "ai_channels",
    channels: "ai_channels",
    ai_channels_settings: "ai_channels",
    payroll: "employees",
    staff: "employees",
    sales_employees: "employees",
    users: "security",
    permissions: "security",
    roles: "security",
    barcode: "barcode_printing",
    barcode_print: "barcode_printing",
    barcode_printing_settings: "barcode_printing",
  };
  if (aliases[value]) return aliases[value];
  return settingsCategories.some((item) => item.key === value) ? value : "";
};

export const getSettingDefinition = (key) => settingsByKey[String(key || "").trim()] || null;
