/**
 * Writes the bidirectional localization debt report and (with --write-baseline)
 * refreshes the guard baseline.
 *
 *   node scripts/i18n-audit.mjs
 *   node scripts/i18n-audit.mjs --write-baseline
 */
import fs from "node:fs";
import path from "node:path";

import { REPO_ROOT, scanRepository, summarise } from "./i18n-scan.mjs";

const reportPath = path.resolve(REPO_ROOT, "docs/localization-debt-report.md");
const baselinePath = path.resolve(REPO_ROOT, "tests/fixtures/i18n-hardcoded-baseline.json");
const writeBaseline = process.argv.includes("--write-baseline");

const { scannedFiles, results } = scanRepository();
const summary = summarise(results);

const lines = [
  "# Localization Debt Report (bidirectional)",
  "",
  "Generated by `npm run i18n:audit`. Regenerate instead of editing by hand.",
  "",
  "This report flags user-visible hardcoded UI strings in the ERP frontend, in **both**",
  "directions: English chrome that will show up in Arabic mode, and Arabic chrome that",
  "will show up in English mode. Storefront, locale bundles and the i18n runtime are out",
  "of scope. The scanner is conservative and can still contain false positives.",
  "",
  "## Summary",
  "",
  `- Source files scanned: ${scannedFiles}`,
  `- Files with debt: ${summary.files}`,
  `- Hardcoded Arabic UI strings: ${summary.arabic}`,
  `- Hardcoded English UI strings: ${summary.english}`,
  `- Total hardcoded UI strings: ${summary.total}`,
  `- Mixed-language files (both scripts hardcoded): ${summary.mixedFiles}`,
  "",
  "### By surface",
  "",
  "| Surface | Files | Arabic | English | Total | Mixed |",
  "| --- | ---: | ---: | ---: | ---: | ---: |",
];

for (const [surface, bucket] of Object.entries(summary.bySurface).sort(([, a], [, b]) => b.total - a.total)) {
  lines.push(`| ${surface} | ${bucket.files} | ${bucket.arabic} | ${bucket.english} | ${bucket.total} | ${bucket.mixedFiles} |`);
}

lines.push("", "## Mixed-language files (ranked by density)", "");
const mixed = results.filter((entry) => entry.arabic > 0 && entry.english > 0);
if (!mixed.length) {
  lines.push("None.", "");
} else {
  lines.push("| File | Surface | Arabic | English | Total |", "| --- | --- | ---: | ---: | ---: |");
  for (const entry of mixed) {
    lines.push(`| ${entry.file} | ${entry.surface} | ${entry.arabic} | ${entry.english} | ${entry.total} |`);
  }
  lines.push("");
}

lines.push("## Per-file detail", "");
for (const entry of results) {
  lines.push(`### ${entry.file} (${entry.surface} — ar:${entry.arabic} en:${entry.english})`, "");
  for (const hit of entry.hits.slice(0, 40)) {
    lines.push(`- ${hit.line} [${hit.type}/${hit.script}] ${hit.value}`);
  }
  if (entry.hits.length > 40) lines.push(`- ... ${entry.hits.length - 40} more`);
  lines.push("");
}

fs.mkdirSync(path.dirname(reportPath), { recursive: true });
fs.writeFileSync(reportPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Localization debt report written to ${path.relative(REPO_ROOT, reportPath)}`);
console.log(
  `files=${summary.files} arabic=${summary.arabic} english=${summary.english} total=${summary.total} mixed=${summary.mixedFiles}`
);

if (writeBaseline) {
  const baseline = {
    note:
      "Localization debt baseline. New hardcoded UI strings are blocked by tests/i18n-hardcoded-guard.test.js. This baseline may only shrink — regenerate with `node scripts/i18n-audit.mjs --write-baseline` after reducing debt.",
    totals: { arabic: summary.arabic, english: summary.english, total: summary.total, mixedFiles: summary.mixedFiles },
    files: Object.fromEntries(
      results
        .slice()
        .sort((a, b) => a.file.localeCompare(b.file))
        .map((entry) => [entry.file, { arabic: entry.arabic, english: entry.english, total: entry.total }])
    ),
  };
  fs.mkdirSync(path.dirname(baselinePath), { recursive: true });
  fs.writeFileSync(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, "utf8");
  console.log(`Baseline written to ${path.relative(REPO_ROOT, baselinePath)}`);
}
