export const CRM_RULES = Object.freeze({
  VIP_SPEND: 10000,
  VIP_ORDERS: 5,
  AT_RISK_DAYS: 45,
  DORMANT_DAYS: 60,
  LOST_DAYS: 180,
  NEW_CUSTOMER_DAYS: 30,
  RECENT_PURCHASE_DAYS: 30,
  RECENT_CONVERSATION_DAYS: 7,
  FAST_RESPONSE_MINUTES: 30,
  HIGH_RETURN_RATE: 0.2,
});

