import { api } from "../../../shared/api/api";

export const staffTasksApi = {
  bootstrap: () => api.get("/staff-tasks/bootstrap"),
  list: (params = {}, options = {}) => api.get("/staff-tasks", { params, ...options }),
  templates: (params = {}, options = {}) => api.get("/staff-tasks/templates", { params, ...options }),
  updateTemplate: (id, payload) => api.put(`/staff-tasks/templates/${id}`, payload),
  my: (params = {}) => api.get("/staff-tasks/my", { params }),
  dashboard: (params = {}, options = {}) => api.get("/staff-tasks/dashboard", { params, ...options }),
  create: (payload) => api.post("/staff-tasks", payload),
  update: (id, payload) => api.put(`/staff-tasks/${id}`, payload),
  updateStatus: (id, payload) => api.patch(`/staff-tasks/${id}/status`, payload),
  complete: (id, payload = {}) => api.post(`/staff-tasks/${id}/complete`, payload),
  addComment: (id, payload) => api.post(`/staff-tasks/${id}/comments`, payload),
  delete: (id) => api.delete(`/staff-tasks/${id}`),
  generateRecurring: (payload = {}) => api.post("/staff-tasks/auto/generate-recurring", payload),
  assignInventoryCounts: (payload = {}) => api.post("/staff-tasks/auto/inventory-counts", payload),
  redistributeAbsent: (payload = {}) => api.post("/staff-tasks/redistribute/absent", payload),
  reassignUnfinished: () => api.post("/staff-tasks/reassign/unfinished", {}),
  employeePortal: (token, options = {}) => api.get("/staff-tasks/employee-portal", { ...options, params: { token } }),
  updateEmployeePortalStatus: (token, id, payload) => api.patch(`/staff-tasks/employee-portal/tasks/${id}/status`, { ...payload, token }),
  completeEmployeePortalTask: (token, id, payload = {}) => api.post(`/staff-tasks/employee-portal/tasks/${id}/complete`, { ...payload, token, status: "completed" }),
  getPortalSettings: (options = {}) => api.get("/staff-tasks/portal-settings", options),
  updatePortalSettings: (payload) => api.put("/staff-tasks/portal-settings", payload),
};
